# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
