# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '本', 'verbose_name_plural': '本'},
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(null=True, verbose_name='発行日'),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='在庫数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=20, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='タイトル'),
        ),
    ]
