# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170614_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '書籍', 'verbose_name_plural': '書籍'},
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='サムネイルurl'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='発行日'),
        ),
    ]
